- name: Submit a GET request to a REST API Endpoint
  hosts: all
  remote_user: ubuntu
  gather_facts: false

  tasks:
    - name: Send GET request to the JSONPlaceholder API
      uri:
        url: https://jsonplaceholder.typicode.com/posts
        method: GET
        return_content: yes
      register: response

    - name: Display the response content
      debug:
        var: response.json

    - name: Show total posts retrieved
      debug:
        msg: Total posts retrieved - {{ response.json | length }}
