- name: Error Handling Real Scenario
  hosts: all
  remote_user: ubuntu
  become_user: root
  gather_facts: true

  vars:
    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes

  tasks:
    - block:
        - name: Install vsftpd
          apt:
            name: vsftpd
            state: present

        - name: Take backup of existing config
          copy:
            src: /etc/vsftpd.conf
            dest: /etc/vsftpd.conf.bkp
            remote_src: true

        - name: Use Jinja2 template to configure vsftpd
          template:
            src: vsftpd.j2
            dest: /etc/vsftpd.conf

        - name: View custom Jinja template values
          command: cat /etc/vsftpd.conf
          register: jinja_out

        - debug: var=jinja_out

        - name: Fail intentionally
          command: ls -l /tmp/non-existent-dir

      become: true

      rescue:
        - name: Recovery block
          debug:
            msg: Something failed, restoring vsftpd.conf from backup

        - name: Restore vsftpd config
          copy:
            src: /etc/vsftpd.conf.bkp
            dest: /etc/vsftpd.conf
            remote_src: true

        - name: View custom Jinja template values
          command: cat /etc/vsftpd.conf
          register: jinja_out

        - debug: var=jinja_out

      always:
        - name: Restart vsftpd
          service:
            name: vsftpd
            state: restarted
