- name: This will show the use of 'Import' module
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Play 1 - Task 1
      debug:
        msg: Play 1 - Task 1

    - import_tasks: tasks-1.yml # Kind of static, parsed during playbook compile-time (message logs don't show explicitly that a module is included)
