- name: This will show the use of comparison operators
  hosts: localhost
  gather_facts: false

  vars:
    a: HELLO
    b: 10
    c: 20
    d: hello

  tasks:
    - name: Operations on variables
      debug:
        msg:
          - The value of b is - {{ b }} and value of c is - {{ c }}
          - Is b > c? - {{ b > c }}
          - Is b < c? - {{ b < c }}
          - Is b >= c? - {{ b >= c }}
          - Is b <= c? - {{ b <= c }}
          - Is b == c? - {{ b == c }}
          - Is b != c? - {{ b != c }}
          - Is a equal to d (case-sensitive)? - {{ a == d }}
          - Is a equal to d (case-insensitive)? - {{ a|lower == d }}
          - Is a < d ? - {{ a < d }}
