- name: This will show the use of logical operators
  hosts: localhost
  gather_facts: false

  vars:
    a: HELLO
    b: 10
    c: 20
    d: hello
    e: [1, 5, 6, 8, 108, 45, 20]
    x: true
    y: false
    z: false
    m: true

  tasks:
    - name: Operations on variables
      debug:
        msg:
          - x and y - {{ x and y }}
          - x or y - {{ x or y }}
          - not x - {{ not x }}
          - not y - {{ not y }}
          - x and m - {{ x and m }}
          - x and y or m - {{ x and y or m }}
